stages:
  - test
  - release

.python_test:
  stage: test
  image: fkrull/multi-python
  variables:
    TOXENV: "flake8,isort,docs"
  before_script:
    - pip install --upgrade pip wheel tox
  script:
    - tox

build:
    image: python:3.8
    stage: release
    before_script:
        - pip install --upgrade setuptools wheel twine
    script:
        - ./setup.py sdist bdist_wheel
        - twine upload dist/*
    only:
        - tags
