language: python
cache: pip

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - env: TOXENV="flake8,isort,docs"
      python: "3.6"

install:
  - pip install --upgrade pip wheel tox-travis

script:
  - tox
