language: python
cache: pip

matrix:
  include:
    - env: TOXENV="py35-{dj20,dj21}-wt26"
      python: '3.5'
    - env: TOXENV="py36-{dj20,dj21}-wt26"
      python: '3.6'
    - env: TOXENV="flake8,isort,docs"
      python: '3.6'

install:
  - pip install --upgrade pip wheel tox

script:
  - tox
